name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            swift: "6.0.3"
            skip_verify_signature: true
          - os: ubuntu-latest
            swift: "6.3.0"
            skip_verify_signature: true
          - os: macos-15
            swift: "6.0.3"
            skip_verify_signature: false
          - os: macos-15
            swift: "6.3.0"
            skip_verify_signature: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Swift
        uses: swift-actions/setup-swift@v3.0.0-beta.1
        with:
          swift-version: ${{ matrix.swift }}
          skip-verify-signature: ${{ matrix.skip_verify_signature }}
      - name: Show Swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
